### ISSUE TITLE
Maintainers: merge up 2 -> master branches

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-postgresql#107]
@silverstripe/core-team 

Some changes recently in the 2.x release line for `PostgreSQLQuery` are conflicting with the master branch, which has also been changed to use generators. I'm not familiar enough with the context to resolve these conflicts myself, so would be nice if someone wouldn't mind doing that!

**Comment by maxime-rainville** [comment]
Yeah, I was about to that. I'm just waiting for confirmation from @sminnee that https://github.com/silverstripe/silverstripe-framework/pull/9098 doesn't require us to increment the required version of Framework.

**Comment by maxime-rainville** [comment]
Just confirmed that `master` is up to date with `2`.
