### ISSUE TITLE
Raw queries API malforms the table name 

### ISSUE THREAD

**Issue by mfendeksilverstripe** [silverstripe/silverstripe-postgresql#110]
I found some issues with raw queries using `PostgreSQL`. Used version is `2.x-dev`

Consider following query:

```
$query = SQLUpdate::create(
    'QueuedJobDescriptor',
    [
        'Expiry' => $expiry,
        'Worker' => $mutex,
        'WorkerCount' => 1,
    ],
    [
        'ID' => $descriptorId,
    ]
);
$query->execute();
```

When I execute it I get the following error:

```
relation "queuedjobdescriptor" does not exist
```

Note that the table name is now all lowercase which matters.

When I rewrite the query like this it works:

```
$query = 'UPDATE "QueuedJobDescriptor" SET "Expiry" = %s , "Worker" = %s'
    . ', "WorkerCount" = 1 WHERE "ID" = %s';

DB::query(sprintf(
    $query,
    Convert::raw2sql($expiry, true),
    Convert::raw2sql($mutex, true),
    Convert::raw2sql($descriptorId)
));
```

I suggest to investigate what happens to table name during the execution of the `SQLUpdate`

EDIT: It seems that all column and table names must be double-quoted. I'm not sure if this is working as intended though.

**Comment by dnsl48** [comment]
> relation "queuedjobdescriptor" does not exist

That error message gets generated by PostgreSQL itself when using unquoted identifiers.
This is the [expected and documented behaviour](https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS).

Potentially, we may consider adding a new feature for this module that would quote table names automatically.

**Comment by ScopeyNZ** [comment]
In your example @mfendeksilverstripe, it's common for framework code to change the table definition like so:

```diff
-    'QueuedJobDescriptor',
+    '"QueuedJobDescriptor"',
```

I agree this definitely feels wrong, but I remember there was a comment from @tractorcow at some point explaining some of the reasoning about how this came about, I just can't find it right now.

**Comment by tractorcow** [comment]
PHPDoc for SQLUpdate() also backs this up.

```
* @param string $table Table name to update (ANSI quoted)
```

> I agree this definitely feels wrong,

This in ansi-92 sql standard, not simply  a silverstripe convention. You need to always ansi quote that parameter. Postgres is a lot stricter about this than mysql.

**Comment by dnsl48** [comment]
I guess we can manually trim doublequotes and pass identifiers into [pg_escape_identifier](https://www.php.net/manual/en/function.pg-escape-identifier.php), which would be more user friendly and a cleaner approach than we do right now.

**Comment by tractorcow** [comment]
Convert::symbol2sql() abstracts symbol (e.g. table, column) escaping at the silverstripe API level. If you implement pg_escape_identifier (override escapeIdentifier) in posgres it'll also do the double quotes, and will be called by symbol2sql().

**Comment by tractorcow** [comment]
E.g. if you don't trust adding double quotes yourself, 

```
$query = SQLUpdate::create(
    Convert::symbol2sql('QueuedJobDescriptor'),
    [
        'Expiry' => $expiry,
        'Worker' => $mutex,
        'WorkerCount' => 1,
    ],
    [
        'ID' => $descriptorId,
    ]
);
$query->execute();
```

If SQL classes receive any unquoted table names (where the phpdoc explicitly expects a quoted table name) it probably wouldn't hurt for it to lazy-escape.

E.g.

```
public function addFrom($from)
    {
        if (is_array($from)) {
            $this->from = array_merge($this->from, $from);
        } elseif (!empty($from)) {
            // Ensure we SQL escape RHS, and un-escape LHS in from array
            $fromRaw = str_replace(array('"','`'), '', $from);
            $this->from[$fromRaw] = Convert::sql2identifier($fromRaw);
        }

        return $this;
    }
```

**Comment by dnsl48** [comment]
>  if you don't trust adding double quotes yourself

I don't trust myself on that :D

My feeling is that ORM APIs could be abstract enough to do this on their own. If we consider the `SQLUpdate::create` method, for example, we can clearly derive that its first argument is a table name, so the method implementation can take care of that on its own, without asking devs to do this manually in almost 100% of cases. Otherwise, if there should be a bit of `raw sql` handled, I'd considered making a separate class-wrapper for raw-sql, that could be handled gracefully by the same method, whereas all string inputs would be considered a table name and to be escaped.

**Comment by tractorcow** [comment]
Sounds good to me. A lot of those "you must quote those parameters" are really just there for legacy reasons that don't make sense in a modern ORM anyway.

**Comment by dhensby** [comment]
I think this discussion should happen on the framework repo if it's going to happen - it's not a driver specific issue.

The `SQLUpdate` and related classes are for building raw queries, they are not part of the ORM domain so have no knowledge or mapping of class names to tables and also shouldn't be opinionated enough to try to quote identifiers for you.

As mentioned previously this is expecte behaviour
