### ISSUE TITLE
Framework DBQueryBuilder::buildUpdateFragment() does not add quotes for table name

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-postgresql#112]
This issue should possibly live in the framwork repo, though it seems like a postgres specific issue

```
$table = DataObject::getSchema()->tableName(File::class);
SQLUpdate::create()
    ->setTable($table)
    // ...
    ->execute();
```

Example of error:
```
UPDATE File

 SET "File"."UserFormUpload" = $1

WHERE ("ID" = $2)

ERROR:  relation "file" does not exist

LINE 1: UPDATE File

               ^
```

https://travis-ci.org/github/silverstripe/silverstripe-userforms/builds/690764092

**Comment by ScopeyNZ** [comment]
Is it actually returning lower case? Normally these issues come up all the time because PostgreSQL is case-insensitive by default, and automatically converts everything to lower case unless you wrap the table name with double quotes in your SQL.

This working code in Elemental implies that it's working:

https://github.com/dnadesign/silverstripe-elemental/blob/4/src/Services/ReorderElements.php#L96-L106

**Comment by emteknetnz** [comment]
Apologies, it's not to do with casing, will update the title of the pull request

Looks like issue is here
https://github.com/silverstripe/silverstripe-framework/blob/4/src/ORM/Connect/DBQueryBuilder.php#L218

`$text = "UPDATE $table";`

seems like it needs to be

`$text = "UPDATE \"$table\"";`

**Comment by emteknetnz** [comment]
OK, think we can close this one.  There's some user error here (me)

The current way when doing `SQLUpdate` type of manipulations is to rely on custom code to manually quote for postgres e.g. `sprintf('"%s"', $tableName)`, rather than doing it centrally within framework.

While this isn't ideal, I don't think there's any pressing need to change this

**Comment by ScopeyNZ** [comment]
I'm almost certain there's an issue floating around somewhere suggesting that we quote identifiers properly in the ORM, but I can't find it. It's not specific to PostgreSQL. 

I wanted to link you to it for your information.
