### ISSUE TITLE
Version 1.2 on Silverstripe 3.7 - Is using schemas for Unit Test temp databases, even with model_schema_as_database set to false

### ISSUE THREAD

**Issue by muppsy007** [silverstripe/silverstripe-postgresql#122]
I have some unit tests that call custom methods that perform alter actions on the database tables to simulate an ETL creating new fields. It looks like by default, tmp tables are created as schemas instead of actual databases like older versions of this module.

Someone on the Slack channel pointed me to the model_schema_as_database setting, which is set to true in the module by default. So I overrode that in my own mysite/_config/postgresql.yml and made it false. However this appears to do nothing (even after a dev/build and even hard deleting cache). I even tried editing the default yaml to see if it was my config. Unit tests are still creating tmp dbs as schemas.

This poses a problem for me as it seems that when these tests run, the logic to check if the new fields exist before creating is done over the public schema (even tho the test is running). Since the field is already in the public schema, it's not added. Yet the test runs across the tmpdb schema, which obviously fails.

Is there a sure fire way to force this module to use databases instead of schemas in unit tests?

**Comment by Cheddam** [comment]
Hey @muppsy007, unfortunately [SilverStripe 3 entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for SilverStripe 3 going forward, and this policy extends to module versions that support SilverStripe 3.

You can read the [SilverStripe Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
