### ISSUE TITLE
1.2.1/Silverstripe 3.7.6 - PostgresSQLDatabase->searchEngine returning an error from it's totalCount query

### ISSUE THREAD

**Issue by muppsy007** [silverstripe/silverstripe-postgresql#125]
Silverstripe Version: 3.7.6
Module Version: 1.2.1
PHP Version: 7.4.16
Postgres Version: 12

I've upgraded a site from 3.1.2 to 3.7.6. Frontend search was already there and functioning fine. It follows the [official Site Search tutorial](https://docs.silverstripe.org/en/3/tutorials/site_search/). The one key difference between the tutorial and this code is that the below exists in it’s own Controller (SearchPage_Controller). Which is routed to from all pages using the route `'search//$Action/$ID/$Batch' : 'SearchPage_Controller'`. Which is clearly working from a route point of view and didn't impact the result action on earlier versions.

```
$searchData = array(
	'Results' => $form->getResults(null,$data),
	'Query' => $form->getSearchQuery(),
	'Title' => _t('SearchForm.SearchResults', 'Search Results')
);
return $this->owner->customise($searchData)->renderWith(array('Page_results', 'Page'));
```

When I submit a search, I get the following error out of [this line in PostgreSQLConnector.php](https://github.com/silverstripe/silverstripe-postgresql/blob/aa16771922c5fd2d943b52bc5aeb98dff3b09d67/code/PostgreSQLConnector.php#L202):

> [Warning] pg_query(): Query failed: ERROR: syntax error at or near ")" LINE 3: WHERE ("ShowInSearch" = ?) ^

The full query being quoted in the stacktrace is:

>SELECT COUNT(*) AS totalitems FROM (SELECT DISTINCT "ClassName", "SiteTree_Live"."ID", "ParentID", "Title", "URLSegment", "Content", "LastEdited", "Created", NULL AS "Filename", NULL AS "Name", "CanViewType", ts_rank("SiteTree_Live"."ts_SearchFields", q) AS "Relevance" FROM "SiteTree_Live" , to_tsquery('english', 'fixed*') AS q WHERE ("ShowInSearch" = ?) AND ("SiteTree_Live"."ts_SearchFields" @@@ q )) AS q1

Looking into this, it appears that a prepared query is being set up, but no parameter passed for "ShowInSearch". If I pump the query direct into my database, changing the ? to 1, it returns fine. I have also found a bit of code in the PostgreSQLDatabase class that is a little odd, and seems to be present in the version 2 branch of code:

* The only place ShowInSearch is mentioned is an assignment to $conditions on [line 323](https://github.com/silverstripe/silverstripe-postgresql/blob/2d11336dce1176d761e02d78d5e7e0f5ff6ec85a/code/PostgreSQLDatabase.php#L323)
* Parameters for the query are setup on [line 348](https://github.com/silverstripe/silverstripe-postgresql/blob/2d11336dce1176d761e02d78d5e7e0f5ff6ec85a/code/PostgreSQLDatabase.php#L348). This seems really strange to me as it does an array_merge on $tableProperties and $parameters, but $tableProperties is always empty, and $parameters doesn't actually exist in the method's scope. Surely I'm missing something there.

I really don't see how PostgreSQLConnector->preparedQuery() can ever get the ShowInSearch parameter here.

**Comment by muppsy007** [comment]
Dug up a bit more detail on this. Mostly comparing to the searchEngine() counterpart in Framework's built in MySQLDatabase method.

* The error here is strictly limited to the result count query in PostgreSQLDatabase->searchEngine(). 
* PostgreSQLDatabase->searchEngine() loops through all the Classes to be searched and at the bottom of each loop, adds to the $tables array using Framework's SQLQuery->sql() method. 
* This SQLQuery->sql() change dramatically at Framework version 3.2 and beyond, so this may be a simple case of the module not keeping up with core changes and test coverage missing it.
* The total count is attempted using the queries returned from SQLQuery->sql(). But it's making a raw DB::query() and the query string from $tables array in this case contains what was originally a prepared statement that still contains a ? placeholder for `ShowInSearch`, instead of the value of 1. I'm not sure if this is simply a change to SQLQuery->sql() once returning a completed sql string, or something changed in this module that is skipping the parameter injection step.

Looking at the difference between the built in MySQLDatabase->searchEngine() method, there's a great deal of difference obviously. But notably in this total count area, MySQL is doing this at the bottom of the loop mentioned above:

```
$querySQLs[] = $query->sql($parameters);
$queryParameters = array_merge($queryParameters, $parameters);

$totalCount += $query->unlimitedRowCount();
```

I have hacked the same into PostgresSQLDatabase and done away with the manual query causing this error. And this works.

```
$tables[] = $query->sql($parameters);
$tableParameters = array_merge($tableParameters, $parameters);

$totalCount += $query->unlimitedRowCount();
```

Would this be something to patch? At present, as far as I can tell, it means that Site Search is not possible with this module on any 3.x site higher than 3.1. I was mistaken about version 2 of this module and SS4. The $table and $tableProperties vars are the same, but they're a red herring. [The $totalCount for version 2 is done quite differently](https://github.com/silverstripe/silverstripe-postgresql/blob/afec73997a055439ef517c954308b65aec0e5186/code/PostgreSQLDatabase.php#L484).

**Comment by muppsy007** [comment]
FYI I also stumbled across another issue in this searchEngine() method. This comes just after the total count and populates the result objects to display on page.

```
$records = $this->preparedQuery($fullQuery, $tableParameters);
foreach($records as $record){
	$objects[] = new $record['ClassName']($record);
}
```

In the case of child class DB records found by search, if the class is an orphan that hasn't been addressed in the CMS, this will trigger a fatal error. Simple case of adding `if(class_exists($record['ClassName'])` before the assignment.

**Comment by ScopeyNZ** [comment]
Unfortunately, [SilverStripe 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for SilverStripe 3 going forward.

You can read the [SilverStripe Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.

I think it's very unlikely someone will look at patching the SS3 version of this module, but you're welcome to PR a patch or maintain a fork for your own use.

**Comment by muppsy007** [comment]
That's the usual line I was expecting.

My question about a fix should be rephrased: I'm not asking if someone else will do the PR. If **I** create a PR, will it be looked at for merging? 

I see PRs sitting there going back to six months. I don't want to waste time with the PR process if it's just going to sit there because due to support commitments. If that's the case, I just need to know. As clearly this is a fundamental feature that will not work for an entire version of the Silverstripe product on Postgres that others who cannot upgrade to SS4 can benefit from. 

If merging PRs to actual broken state are a no go due to roadmaps, that's fine. I'll find another solution. I just need to know if that's the case or not. If someone will still merge other people's PRs despite those roadmaps, I'll do that.

**Comment by ScopeyNZ** [comment]
We still sometimes review PRs that target versions of 3, but usually it still requires having a copy of 3 installed and testing the PR by hand - which is a tough ask when most of us haven't touched it in a couple of years now. I think that's why the 3 PRs usually sit around. If we do test and merge, it's not certain that we'll create a release for it. 

I personally barely have time right now to work on SilverStripe at all, so I probably won't personally review a PR. The contributors hired by SSLtd. are also pretty spread thin. I honestly think your best bet will be maintaining a fork.

**Comment by muppsy007** [comment]
Thanks for clarifying @ScopeyNZ
