### ISSUE TITLE
Eager loading test is failing on PostgreSQL

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-postgresql#149]
Our builds are failing wit the new eager loading feature.

The problem is not with eager loading but with some logic for building fixture.

I think the test themselves have some order comparison issue.

## Pull requests
- https://github.com/silverstripe/silverstripe-postgresql/pull/148
- https://github.com/silverstripe/silverstripe-framework/pull/10848

**Comment by GuySartorelli** [comment]
Merged

**Comment by GuySartorelli** [comment]
Reopening and assigning to @maxime-rainville at his request per https://github.com/silverstripe/silverstripe-framework/pull/10848#issuecomment-1617309407

**Comment by maxime-rainville** [comment]
Sorry, I meant to post this comment here.

Build is green now.
