### ISSUE TITLE
Query compartibility problems: Limit and Order does not work for PostgreSQL

### ISSUE THREAD

**Issue by wilr** [silverstripe/silverstripe-postgresql#15]
From http://open.silverstripe.org/ticket/7632

Found in lazy loading an issue when I use postgres:
- the order column is not quoted which causes problems in postgres
- limit syntax in postgres is different as implemented (need to use offset, combined with limit).

"I think this was broken in mid June by a commit allowing backslashes in database table names. It stuffed up all the other DB drivers as well... I've fixed SQLite3, those commit might help to track down the problem:  https://github.com/silverstripe-labs/silverstripe-sqlite3/commits/master"

**Comment by dhensby** [comment]
5 years old and no other complaints about this.. closing
