### ISSUE TITLE
Postgres alternate time zone support

### ISSUE THREAD

**Issue by wilr** [silverstripe/silverstripe-postgresql#16]
http://open.silverstripe.org/ticket/4542.

Ticket #3910 suggested a way to add time zone support for a time zone different to that of the server the database is on (added in r85716). It would be good to also add this enhancement to the postgres and ms sqlserver database connector classes.

Syntax for postgres is:

SET SESSION TIME ZONE 'Europe/Rome?';

(see  http://www.postgresql.org/docs/8.1/interactive/sql-set.html)

I couldn't find the appropriate documentation for how to do this in SQLServer.

**Comment by dhensby** [comment]
fixed
