### ISSUE TITLE
Indexes schema update bugs

### ISSUE THREAD

**Issue by wilr** [silverstripe/silverstripe-postgresql#18]
If you try to add an index, which has string spec, it fails. For example, this will fail:

```php
function extraStatics() { 
return array( 
'indexes' => array('External_Anchor' => 'index (External_Anchor)') 
); 
}
```

This case is from External_auth module ... I'm not shure, if string specification of indexes is valid, cause I can't find documentation/specification on it. Anyway, in MySql? it passes.

If you try to add an index on a field, which has underscore in it, it fails, or rather it fails detecting it on subsequent db scans. For example:

```php
function extraStatics() { 
return array( 
'indexes' => array('External_Anchor' => true) 
); 
}
```

This is down to very buggy/inconsistent index name handling in Postgresql module, which is scattered around in many functions: getIndexSqlDefinition, getDbSqlDefinition, indexList, modifyIndex... For example, to find out, if the index exists, module compares indexname given in indexSchema with index name calculated from fields used in index (done in function indexList) - but these two things can be completely different! So for example, this will always fail - or better, it'd fail detecting it on second db scan...:

```php
function extraStatics() { 
return array( 
'indexes' => array('CustomIndexName' => '(field1)') 
); 
}
```

Test

```php
<?php
class TestPage extends Page {
    public static $db = array(
        'Test_field' => 'Text',
        'TestField2' => 'Text',
    );
    public static $indexes = array(
        'Test_field' => true,
        'CustomIndexExample' => array('type' => 'index', 'value' => 'TestField2')  
    );
}
```

**Comment by dhensby** [comment]
the way indexes are defined in SS 4 is now much more prescriptive and doesn't allow for string definitions.
