### ISSUE TITLE
Support different port during install

### ISSUE THREAD

**Issue by ggaborx** [silverstripe/silverstripe-postgresql#23]
I just tried to install silverstripe on my postgresql database. I use it on 5491 port so I entered localhost:5491 but it failed to install. I figured out that in requireDatabase\* function the port number was hardcoded:

$connstring = "host=$server port=5432 dbname=postgres {$userPart}{$passwordPart}";

I suggest to explode $databaseConfig['server'] then use first part as $server and if exist second part as port in both checking functions.

**Comment by dhensby** [comment]
This would be an issue that should be reported on framework, really.

As this is 5 years old and we haven't had others agree this is a problem *and* we definitely encourage configuration through `.env` (or `_ss_environment.php` in SS 3) I see this as a very low impact bug that likely won't be fixed unless someone volunteers their time to do it.

if your set up is advanced enough that you use a non-standard port, you should be advanced enough to not be using the installer to get SS working.
