### ISSUE TITLE
Case sensitivity causes grief during installs

### ISSUE THREAD

**Issue by RantyDave** [silverstripe/silverstripe-postgresql#37]
While the github page for silverstripe-postgresql alludes to names needing to be double quoted to avoid case insensitivity, the installer doesn't mention this and mixed case table name causes database errors.

**Comment by RantyDave** [comment]
Noting also that this means attaching a user that can't create databases to a database that already (apparently) has a correct database name i.e. "SS_mysite" fails.

**Comment by phptek** [comment]
Yeah just fallen over this too, but during dev. One of the (admittedly many) ideas behind an ORM is the abstraction. Theoretically, I should be able to use PostGres or MySQL or MSSQL, with all thw differences in SQL syntax abstracted from me, and in the main this is exactly what it does.

But...if this is true, and quoting fields and tables is requiored by postgres, then shouldn't the module - its being a component of the ORM in this case - abstract this away too?

**Comment by dhensby** [comment]
The ORM should be quoting all DB identifiers - do you know where the unquoted identifiers are coming from?

**Comment by tractorcow** [comment]
ORM has changed significantly, and we pretty much have addressed all the un-quoted table identifiers by now. Closing.
