### ISSUE TITLE
PDO Broken due to unsupported "charset" parameter

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-postgresql#44]
Rather than including 'charset=' in the pdo connection string we'll need to set the `set client_encoding` parameter on connect.

See http://stackoverflow.com/questions/18250167/how-set-utf-8-in-pdo-class-constructor-for-php-pgsql-database

**Comment by kinglozzer** [comment]
It’s also currently broken (for me anyway) because it seems to be using the wrong driver name: `postgresql` instead of `pgsql`

**Comment by tractorcow** [comment]
FIxed with https://github.com/silverstripe/silverstripe-postgresql/pull/78
