### ISSUE TITLE
Space in ENUM value causes issue

### ISSUE THREAD

**Issue by ColmMcBarron** [silverstripe/silverstripe-postgresql#54]
There seems to be an issue when you have spaces in your enum values and the item cannot be saved.

Defining the field:

`
private static $db = array(
    "MyEnumField" => "Enum('Value A, Value B, Value C')"
);
`

and using i like this:

`
$fields->addFieldToTab('Root.MyTab', new DropdownField('MyEnumField','MyEnumField',singleton('MyContentType')->dbObject('MyEnumField')->enumValues()));
`

After rebuilding the database, when I save a record I get:

PHP Warning:  pg_query_params(): Query failed: ERROR:  new row for relation &quot;MyContentType&quot; violates check constraint &quot;MyContentType_MyEnumField_check&quot;\nDETAIL:  Failing row contains (1, Value C). in /xx/postgresql/code/PostgreSQLConnector.php on line 200, referer: http://localhost:8888/admin/pages/edit/show/1

If there are no spaces in the Enum names this works perfectly fine.

**Comment by dhensby** [comment]
Is this specifically a postgres issues?
