### ISSUE TITLE
Altering field type raises Exception

### ISSUE THREAD

**Issue by phptek** [silverstripe/silverstripe-postgresql#64]
PHP 5.6 / module version 1.2.x-dev / Postgres 9.5 on Ubuntu 16.04

If I create a standard field of seemingly any field-type and ALTER it by means of changing the type in a model's `$db` static and run dev/build flush=all, _two_ or _three_ times, I will see an uncaught `SS_DatabaseException`.

Reproduction - Scenario #1

```
    // 1). OK
    private static $db = [
        'TEST44' => 'Varchar',
   ];
```

```
    // 2). FAIL
    private static $db = [
        'TEST44' => 'Int',
   ];
```

Reproduction - Scenario #2

```
    // 1). OK
    private static $db = [
        'TEST44' => 'Boolean',
   ];
```

```
    // 2). OK
    private static $db = [
        'TEST44' => 'Varchar',
   ];
```

```
    // 2). FAIL
    private static $db = [
        'TEST44' => 'Varchar',
   ];
```

```
PHP Warning:  pg_query(): Query failed: ERROR:  column "TEST44" cannot be cast automatically to type integer
HINT:  You might need to specify "USING "TEST44"::integer". in /path/to/postgresql/code/PostgreSQLConnector.php on line 202
ERROR [User Error]: Uncaught SS_DatabaseException: Couldn't run query:

ALTER TABLE "ProductGenerator" ALTER COLUMN "TEST44" TYPE integer
,
ALTER COLUMN "TEST44" DROP DEFAULT,
ALTER COLUMN "TEST44" SET default 0

ERROR:  column "TEST44" cannot be cast automatically to type integer
HINT:  You might need to specify "USING "TEST44"::integer".
IN GET /dev/build
Line 55 in /path/to/framework/model/connect/DBConnector.php
```

**Comment by phptek** [comment]
I've also seen it with a `Varchar(6)` being changed to `Varchar(3)`.

**Comment by phptek** [comment]
Running the same query manually via the postgres client I see the same error. Adding its helpful suggestion, seems to work:

```
ALTER TABLE "ProductGenerator" ALTER COLUMN "TEST44" TYPE integer USING "TEST44"::integer;
```

**Comment by phptek** [comment]
Note re: the PR #65 was branched off 1.2, but a ton of work has obviously been done since and pushed into master, hence the conflicts. I can rebase the branch against `master` but cannot test it locally, as the module is being used in a v3.5 project.

**Comment by phptek** [comment]
Rebased against master and force-pushed back to #issue/64

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-postgresql/pull/65
