### ISSUE TITLE
Install using pg_connect incorrectly reports it cannot ALTER tables

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-postgresql#66]
Migrated from https://github.com/silverstripe/silverstripe-framework/issues/3951

----

While installing dev-master @ 26.2.15 pg_connect reports it cannot alter tables:

![silverstripe_cms___framework_installation](https://cloud.githubusercontent.com/assets/4230547/6407369/bb31e076-bea3-11e4-8c0a-f45f457f4a53.png)

Doing it through PGAdmin, however:
![pgadmin_iii](https://cloud.githubusercontent.com/assets/4230547/6407386/4f6bb32a-bea4-11e4-8f16-d3b61c7443d3.png)

![query_-_stripe_on_stripe_zedkep_com_5432___and_pgadmin_iii_and_new_issue_ _silverstripe_silverstripe-framework](https://cloud.githubusercontent.com/assets/4230547/6407404/7282540e-bea4-11e4-985a-cfa06793df99.png)

and we're good to go...

![pgadmin_iii](https://cloud.githubusercontent.com/assets/4230547/6407433/c84e4b72-bea4-11e4-9bd5-9bc31bb0b591.png)

----

OK, so it appears the problem is in https://github.com/silverstripe/silverstripe-postgresql/blob/master/code/PostgreSQLDatabaseConfigurationHelper.php#L179-192. According to Postegresql's docs there is no "create" role (http://www.postgresql.org/docs/9.4/static/functions-info.html).

"The desired access privilege type is specified by a text string, which must evaluate to one of the values SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, or TRIGGER". 

To make things worse I don't know if the code is actually trying to test for the ability to alter or the ability to create a database and/or table. FWIW I created a user with default permissions + ability to create new databases:

![login_role_stripe](https://cloud.githubusercontent.com/assets/4230547/6432282/7cc4d29e-c0b0-11e4-8cbb-9be366738dc2.png)

And that has no problem creating databases, tables and altering. A user that doesn't have privileges for creating a database can still alter tables.

So, the problem I have is in understanding what this function is supposed to do. It tests for "create" but reports a problem with "ALTER". Should it just return (true, true) since it appears one can alter a table that one has permissions for? Also, there appears to be two different techniques for testing permissions in play - see line 168.

BTW, this also means this bug report is listed under the wrong module, should be silverstripe/postgresql.

**Comment by maxime-rainville** [comment]
I didn't manage to replicate this on Postgress 10.4 with SS4x. The installer worked like a charm for me.

**Comment by dhensby** [comment]
Great. No one has complained about this in a year, so let's say it's fixed :)
