### ISSUE TITLE
New page types are not picked up

### ISSUE THREAD

**Issue by ColmMcBarron** [silverstripe/silverstripe-postgresql#71]
I have recently been having a problem with new page types are not picked up, after debugging, and eventually resolving the issue, here is the problem.

When running unit tests, the temp test database is not cleaned up if there is an error/test failure.

In the postgres module, contraints are used as a pseudo ENUM to ensure the appropriate sub-classes are available.

The problem is that the lookup for these contraints picks up all contraint with that name and simply takes the first one.

There needs to be a better way to do this, so these head-scratching collisions do not take place!

Probably a slightly different query to get the contraints will work, for now my work around is to ensure my test databases are destroyed.

**Comment by dhensby** [comment]
What version of SS are you using?

**Comment by ColmMcBarron** [comment]
3.6

**Comment by tractorcow** [comment]
> with new page types are not picked up,

What do you mean by not picked up; If you save a record with a new page type, do you mean the DB value violates the constraint and raises an error?

> When running unit tests, the temp test database is not cleaned up if there is an error/test failure.

Do you encounter this error only when running tests, or also when using the CMS?

> The problem is that the lookup for these contraints picks up all contraint with that name and simply takes the first one.

Can you give an example please, or point to the code that has this error? That way I can help reproduce this error.

Thanks!

**Comment by ColmMcBarron** [comment]
Sorry, should have been clearer.

When I say the new page types are not being picked up, what I mean is that while the database builds fine through dev/build and sets the appropriate contraint key, when you want to check it in the UI or add a new type of page, the new page is absent from the list.

I tracked this down to
branch 1.2:
https://github.com/silverstripe/silverstripe-postgresql/blob/1.2/code/PostgreSQLSchemaManager.php#L877

However, I notice this has changed in master, which seems to address this issue using the additional parameter in the query: `n.nspname = ?`:
https://github.com/silverstripe/silverstripe-postgresql/blob/master/code/PostgreSQLSchemaManager.php#L908

My tests pass fine because the database has updated, just the list of page types wasn't returning fully, which is not something I would have in my tests.

**Comment by tractorcow** [comment]
If we back-port that fix to 1.2 branch would that be sufficient? I recall that this issue came about because the test db was on the same master DB, but different only by schema, so there was some inconsistencies running unit tests.

**Comment by tractorcow** [comment]
See original PR for context https://github.com/silverstripe/silverstripe-postgresql/pull/48

**Comment by dhensby** [comment]
No reply for a year
