### ISSUE TITLE
Tag a 4.0 comatible release

### ISSUE THREAD

**Issue by Mossman1215** [silverstripe/silverstripe-postgresql#79]
in the readme the instructions state to run `composer` require silverstripe/postgresql 1.2.*-dev`
which results in `Your requirements could not be resolved to an installable set of packages.` because I am running php7 and framework 4.
1.2 is setup for PHP5.6 and framework 3.7 or lower.
I have cloned master branch and I'll see how that goes.
This is a note for me to look at later

**Comment by tractorcow** [comment]
You can use 2.0.0-beta1.

I've removed the version constraint in the docs at https://github.com/silverstripe/silverstripe-postgresql/commit/1277361a6c015f025e05c538ff05f410789a8055
