### ISSUE TITLE
PostgreSQLConnector: Return strict PHP types in results

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-postgresql#90]
`pg_fieldtype` should, in principle, be able to be used to cast boolean, integer, and float values to the correct PHP types.

This affects PostgreSQLConnector but not PGSQL access through PDOConnector.

This will help complete implementation of https://github.com/silverstripe/silverstripe-framework/pull/8448.

**Comment by NightJar** [comment]
This would certainly be ideal, I just ran into this issue today :)

**Comment by sminnee** [comment]
The linked framework ticket addresses it in MySQL / PDO code. This would just be the last hurdle.
